component: express
name: expressDemo
org: orgDemo
app: coldknowledge
stage: dev
inputs:
  src:
    src: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
